draw_smooth_squares_interface:
    resource: "@DrawSmoothSquaresInterfaceBundle/Resources/config/routing.yml"
    prefix:   /

draw_smooth_score_getter:
    resource: "@DrawSmoothScoreGetterBundle/Resources/config/routing.yml"
    prefix:   /



