landing:
    pattern:  /
    defaults: { _controller: DrawSmoothScoreGetterBundle:Default:index }

gamesList:
    pattern:  /gamesList
    defaults: { _controller: DrawSmoothScoreGetterBundle:Default:gamesList }
