parameters:
#    draw_smooth_score_getter.example.class: DrawSmooth\ScoreGetterBundle\Example

services:
#    draw_smooth_score_getter.example:
#        class: %draw_smooth_score_getter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
